# Generated by Django 5.1.1 on 2024-10-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjama',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
