# Generated by Django 5.1.1 on 2024-10-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tarjama_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjama',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
