# Generated by Django 5.1.1 on 2024-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_art_mois_art_mois_tahmich'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_mois',
            name='data_h',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
