# Generated by Django 5.1.1 on 2024-10-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_art_mois_data_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.TextField()),
            ],
        ),
    ]
