# Generated by Django 5.1.1 on 2024-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_image_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_mois',
            name='image',
        ),
        migrations.AlterField(
            model_name='image_art',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
